### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by rewgoes** [rewgoes/PopularMovies#20]
FAILED BINDER TRANSACTION !!!  (parcel size = 531744)
Shutting down VM
FATAL EXCEPTION: main
Process: com.wolfgoes.popularmovies, PID: 12191
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 531744 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4167)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: android.os.TransactionTooLargeException: data parcel size 531744 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:628)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:4132)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4159)
	... 7 more

**Comment by rewgoes** [comment]
https://stackoverflow.com/questions/41953195/fragment-save-large-list-of-data-on-onsaveinstancestate-how-to-prevent-transac

**Comment by rewgoes** [comment]
The problem is in onSaveInstanceState in MoviesFragment.java
